---
language: rust
os:
  - linux
  - osx
rust:
  - nightly
  - beta
  - stable
  - 1.32.0  # pinned minimum supported toolchain

matrix:
  allow_failures:
    - rust: nightly
  include:
    - name: "Lints with stable toolchain"
      os: linux
      arch: amd64
      rust: stable
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        # Ideally we would run CLippy on all targets, but benchmarks depend
        # on an unstable feature and only work on nightly.
        # - cargo clippy --all-targets -- -D warnings
        - cargo clippy -- -D warnings -W clippy::match-same-arms
        - cargo clippy --tests -- -D warnings -W clippy::match-same-arms


# bors default configuration:
# branches:
#   only:
#     # This is where pull requests from "bors r+" are built.
#     - staging
#     # This is where pull requests from "bors try" are built.
#     - trying
#     # Uncomment this to enable building pull requests.
#     #- master
#
# Instead, we can just disable bors temporary branches.
branches:
  except:
    - staging.tmp
    - trying.tmp

script:
  - cargo build --verbose
  - cargo test  --verbose
  - cargo build --verbose --all-features
  - cargo test  --verbose --all-features
