[package]
name = "lzma"
version = "0.1.0"
authors = ["Guillaume Endignoux <ggendx@gmail.com>"]
exclude = ["tests/"]

[dependencies]
log = "0.3"

[dev-dependencies]
env_logger = "0.3"

[badges]
travis-ci = { repository = "gendx/lzma-rs", branch = "master" }
